name: es3fny_user_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hexcolor: ^3.0.1
  font_awesome_flutter: ^10.2.1
  smooth_page_indicator: ^1.0.0+2
  pin_code_fields: ^7.4.0
  fluttertoast: ^8.1.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_markdown: ^0.6.12
  iconsax: ^0.0.8
  fluentui_system_icons: ^1.1.185
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  flutter_windowmanager: ^0.2.0
  intl_phone_number_input: ^0.7.1
  shared_preferences: ^2.0.15
  lottie: ^2.0.0
  motion_toast: ^2.6.4
  dropdown_button2: ^1.9.2
  sqflite: ^2.2.2
  conditional_builder_null_safety: ^0.0.6
  pretty_dio_logger: any
  flutter_slidable: ^2.0.0
  path:
  dio: ^5.0.1
  flutter_tts: ^3.6.3
  speech_to_text: ^6.1.1
  avatar_glow: ^2.0.2
  syncfusion_flutter_datepicker: "20.4.44"
  equatable: ^2.0.3

  google_maps_flutter: ^2.2.5
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.2
  material_floating_search_bar: ^0.3.7

  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/
    - assets/lottie/
    - assets/lang/en.json
    - assets/lang/ar.json

  fonts:
    - family: Almarai-Bold
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
    - family: Almarai-Regular
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400

    - family: Rubik-Light
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300

    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500