String? token;
String? userId;
String? otpCodeFromShared;
String? langCode = '';
int? langContainerIndex = 0;
bool isDark = false;
int isBlind = 1;
const String googleApiKey = "AIzaSyDUNaxTG6FDCGz51xE-Uc9ZoEAbHsawv8M";
double? currentLatitude;
double? currentLongitude;
double distance = 0;